export let dataQuiz = [
  {
    id: Math.random(),
    question: "HTML means Hyper Text Marking Language.",
    response: ["True", "False"],
    correct: "False",
    category: "HTML",
  },
  {
    id: Math.random(),
    question: "Attributes are placed :",
    response: [
      "after the opening tag.",
      "in the opening tag.",
      "in the closing tag.",
    ],
    correct: "In The Opening Tag.",
    category: "HTML",
  },
  {
    id: Math.random(),
    question: "Why do we use local links?",
    response: [
      "To Allow Users To Navigate In The Same Web Page",
      "To Navigate Between Different Web Pages",
      "To Navigate Without Using The Internet",
    ],
    correct: "To Allow Users To Navigate In The Same Web Page",
    category: "HTML",
  },
  {
    id: Math.random(),
    question:
      "The <form> tag is the only necessary tag to get the user’s inputs.",
    response: ["True", "False"],
    correct: "False",
    category: "HTML",
  },
  {
    id: Math.random(),
    question:
      "With external CSS, you can write the CSS code in an external file (with the .CSS extension) and import it in the <body>",
    response: ["True", "False"],
    correct: "False",
    category: "CSS",
  },
  {
    id: Math.random(),
    question: "Margin is the OUTSIDE of the element?",
    response: ["True", "False"],
    correct: "True",
    category: "CSS",
  },
  {
    id: Math.random(),
    question: "What does CSS stand for?",
    response: [
      "Coded Style Sheet",
      "Coding Style Separately",
      "Creating Sweet Styles",
      "Cascading Style Sheets",
    ],
    correct: "Cascading Style Sheets",
    category: "CSS",
  },
  {
    id: Math.random(),
    question: "A CSS rule consists of:",
    response: [
      "a selector and a declaration",
      "a selector and a property value",
      "a property name and property value",
      "a declaration and a property name",
    ],
    correct: "a selector and a declaration",
    category: "CSS",
  },
  {
    id: Math.random(),
    question: "CSS selectors can be ....",
    response: [
      "A tag name, a class or a title",
      "A class, an ID or a title",
      "A tag name, an ID or a class",
      "Any HTML tag that has style attribute",
    ],
    correct: "A tag name, an ID or a class",
    category: "CSS",
  },
  {
    id: Math.random(),
    question:
      "To use flexbox we define a container as a flexbox. What is the CSS to do this?",
    response: [
      "position:absolute;",
      "float:left;",
      "display:flex;",
      "display:block;",
    ],
    correct: "display:flex;",
    category: "CSS",
  },
  {
    id: Math.random(),
    question: "Inside which HTML element do we put the JavaScript?",
    response: ["<script>", "<js>", "<scripting>", "<javascript>"],
    correct: "<script>",
    category: "JS",
  },
  {
    id: Math.random(),
    question:
      "What is the correct JavaScript syntax to change the content of the HTML element below? <p id='demo'>This is a demonstration.</p>",
    response: [
      'document.getElementById("demo").innerHTML = "Hello World!";',
      'document.getElement("p").innerHTML = "Hello World!"',
      'document.getElementByName("p").innerHTML = "Hello World!";',
      '#demo.innerHTML = "Hello World!";',
    ],
    correct: 'document.getElementById("demo").innerHTML = "Hello World!";',
    category: "JS",
  },
  {
    id: Math.random(),
    question: "Where is the correct place to insert a JavaScript?",
    response: [
      "The <body> section",
      "Both the <head> section and the <body> section are correct",
      "The <head> section",
    ],
    correct: "Both the <head> section and the <body> section are correct",
    category: "JS",
  },
  {
    id: Math.random(),
    question:
      'What is the correct syntax for referring to an external script called "xxx.js"?',
    response: [
      '<script name="xxx.js">',
      '<script href="xxx.js">',
      '<script src="xxx.js">',
    ],
    correct: '<script src="xxx.js">',
    category: "JS",
  },
  {
    id: Math.random(),
    question: "The external JavaScript file must contain the <script> tag",
    response: ["True", "False"],
    correct: "False",
    category: "JS",
  },
  {
    id: Math.random(),
    question: 'How do you write "Hello World" in an alert box?',
    response: [
      'msgBox("Hello World");',
      'msg("Hello World");',
      'alert("Hello World");',
      'alertBox("Hello World");',
    ],
    correct: 'alert("Hello World");',
    category: "JS",
  },
  {
    id: Math.random(),
    question: "How do you create a function in JavaScript?",
    response: [
      "function:myFunction()",
      "function myFunction()",
      "function = myFunction()",
    ],
    correct: "function myFunction()",
    category: "JS",
  },
  {
    id: Math.random(),
    question: 'How do you call a function named "myFunction"?',
    response: [
      "call myFunction()",
      "call function myFunction()",
      "myFunction()",
    ],
    correct: "myFunction()",
    category: "JS",
  },
  {
    id: Math.random(),
    question: "How to write an IF statement in JavaScript?",
    response: ["if i == 5 then", "if i = 5", "if (i == 5)", "if i = 5 then"],
    correct: "if (i == 5)",
    category: "JS",
  },
  {
    id: Math.random(),
    question:
      'How to write an IF statement for executing some code if "i" is NOT equal to 5?',
    response: ["if i =! 5 then", "if (i <> 5)", "if i <> 5", "if (i != 5)"],
    correct: "if (i != 5)",
    category: "JS",
  },
  {
    id: Math.random(),
    question: "How does a WHILE loop start?",
    response: ["while i = 1 to 10", "while (i <= 10; i++)", "while (i <= 10)"],
    correct: "while (i <= 10)",
    category: "JS",
  },
  {
    id: Math.random(),
    question: "How does a FOR loop start?",
    response: [
      "for i = 1 to 5",
      "for (i = 0; i <= 5)",
      "for (i = 0; i <= 5; i++)",
      "for (i <= 5; i++)",
    ],
    correct: "for (i = 0; i <= 5; i++)",
    category: "JS",
  },
  {
    id: Math.random(),
    question: "What is the correct way to write a JavaScript array?",
    response: [
      'var colors = (1:"red", 2:"green", 3:"blue")',
      'var colors = "red", "green", "blue"',
      'var colors = ["red", "green", "blue"]',
      'var colors = 1 = ("red"), 2 = ("green"), 3 = ("blue")',
    ],
    correct: 'var colors = ["red", "green", "blue"]',
    category: "JS",
  },
  {
    id: Math.random(),
    question: "Which event occurs when the user clicks on an HTML element?",
    response: ["onchange", "onclick", "onmouseclick", "onmouseover"],
    correct: "onclick",
    category: "JS",
  },
  {
    id: Math.random(),
    question: "What will the following code return: Boolean(10 > 9)",
    response: ["True", "False", "NaN"],
    correct: "True",
    category: "JS",
  },
];
